name: hubmap-cell-sets
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - scipy
  - pandas
  - networkx
  - snakemake
  - nb_conda
  - anndata==0.7.1
  - pyarrow==0.15.1
  - h5py==2.10.0
  - pyyaml
  - pip
  - pip:
    - obonet