name: vitessce-demo-cell-type-annotations
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - scipy==1.4.1
  - networkx==2.4
  - snakemake==5.17.0
  - anndata==0.7.1
  - pyarrow==0.15.1
  - h5py==2.10.0
  - pip
  - pip:
    - obonet==0.2.5